/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedBlogsRouteImport } from './routes/_authenticated/blogs'
import { Route as AuthenticatedBookCallsRouteImport } from './routes/_authenticated/book-calls'
import { Route as AuthenticatedCmsRouteImport } from './routes/_authenticated/cms'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDemoRequestsRouteImport } from './routes/_authenticated/demo-requests'
import { Route as AuthenticatedEnterpriseRequirementsRouteImport } from './routes/_authenticated/enterprise-requirements'
import { Route as AuthenticatedInstructorApplicationsRouteImport } from './routes/_authenticated/instructor-applications'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedNewsletterRouteImport } from './routes/_authenticated/newsletter'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSystemHealthRouteImport } from './routes/_authenticated/system-health'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'
import { Route as SiteProductsIndexRouteImport } from './routes/_site/products.index'
import { Route as SiteProductsSlugRouteImport } from './routes/_site/products.$slug'
import { Route as SiteServicesIndexRouteImport } from './routes/_site/services.index'
import { Route as SiteServicesSlugRouteImport } from './routes/_site/services.$slug'
import { Route as SiteTrainingIndexRouteImport } from './routes/_site/training.index'
import { Route as SiteTrainingSlugRouteImport } from './routes/_site/training.$slug'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBlogsRoute = AuthenticatedBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookCallsRoute = AuthenticatedBookCallsRouteImport.update({
  id: '/book-calls',
  path: '/book-calls',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCmsRoute = AuthenticatedCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoRequestsRoute =
  AuthenticatedDemoRequestsRouteImport.update({
    id: '/demo-requests',
    path: '/demo-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnterpriseRequirementsRoute =
  AuthenticatedEnterpriseRequirementsRouteImport.update({
    id: '/enterprise-requirements',
    path: '/enterprise-requirements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstructorApplicationsRoute =
  AuthenticatedInstructorApplicationsRouteImport.update({
    id: '/instructor-applications',
    path: '/instructor-applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsletterRoute = AuthenticatedNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSystemHealthRoute =
  AuthenticatedSystemHealthRouteImport.update({
    id: '/system-health',
    path: '/system-health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsIndexRoute = SiteProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProductsSlugRoute = SiteProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesIndexRoute = SiteServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesSlugRoute = SiteServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrainingIndexRoute = SiteTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrainingSlugRoute = SiteTrainingSlugRouteImport.update({
  id: '/training/$slug',
  path: '/training/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/book-calls': typeof AuthenticatedBookCallsRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo-requests': typeof AuthenticatedDemoRequestsRoute
  '/enterprise-requirements': typeof AuthenticatedEnterpriseRequirementsRoute
  '/instructor-applications': typeof AuthenticatedInstructorApplicationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/newsletter': typeof AuthenticatedNewsletterRoute
  '/products': typeof AuthenticatedProductsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/users': typeof AuthenticatedUsersRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/training/$slug': typeof SiteTrainingSlugRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/products/': typeof SiteProductsIndexRoute
  '/services/': typeof SiteServicesIndexRoute
  '/training/': typeof SiteTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/blogs': typeof AuthenticatedBlogsRoute
  '/book-calls': typeof AuthenticatedBookCallsRoute
  '/cms': typeof AuthenticatedCmsRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demo-requests': typeof AuthenticatedDemoRequestsRoute
  '/enterprise-requirements': typeof AuthenticatedEnterpriseRequirementsRoute
  '/instructor-applications': typeof AuthenticatedInstructorApplicationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/newsletter': typeof AuthenticatedNewsletterRoute
  '/products': typeof SiteProductsIndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/services': typeof SiteServicesIndexRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/system-health': typeof AuthenticatedSystemHealthRoute
  '/users': typeof AuthenticatedUsersRoute
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/products/$slug': typeof SiteProductsSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/training/$slug': typeof SiteTrainingSlugRoute
  '/blog': typeof SiteBlogIndexRoute
  '/training': typeof SiteTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/blogs': typeof AuthenticatedBlogsRoute
  '/_authenticated/book-calls': typeof AuthenticatedBookCallsRoute
  '/_authenticated/cms': typeof AuthenticatedCmsRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demo-requests': typeof AuthenticatedDemoRequestsRoute
  '/_authenticated/enterprise-requirements': typeof AuthenticatedEnterpriseRequirementsRoute
  '/_authenticated/instructor-applications': typeof AuthenticatedInstructorApplicationsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/newsletter': typeof AuthenticatedNewsletterRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/system-health': typeof AuthenticatedSystemHealthRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/products/$slug': typeof SiteProductsSlugRoute
  '/_site/services/$slug': typeof SiteServicesSlugRoute
  '/_site/training/$slug': typeof SiteTrainingSlugRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/products/': typeof SiteProductsIndexRoute
  '/_site/services/': typeof SiteServicesIndexRoute
  '/_site/training/': typeof SiteTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/blogs'
    | '/book-calls'
    | '/cms'
    | '/courses'
    | '/dashboard'
    | '/demo-requests'
    | '/enterprise-requirements'
    | '/instructor-applications'
    | '/leads'
    | '/newsletter'
    | '/products'
    | '/profile'
    | '/services'
    | '/settings'
    | '/system-health'
    | '/users'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/training/$slug'
    | '/blog/'
    | '/products/'
    | '/services/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity'
    | '/blogs'
    | '/book-calls'
    | '/cms'
    | '/courses'
    | '/dashboard'
    | '/demo-requests'
    | '/enterprise-requirements'
    | '/instructor-applications'
    | '/leads'
    | '/newsletter'
    | '/products'
    | '/profile'
    | '/services'
    | '/settings'
    | '/system-health'
    | '/users'
    | '/about'
    | '/contact'
    | '/blog/$slug'
    | '/products/$slug'
    | '/services/$slug'
    | '/training/$slug'
    | '/blog'
    | '/training'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_site'
    | '/login'
    | '/_authenticated/activity'
    | '/_authenticated/blogs'
    | '/_authenticated/book-calls'
    | '/_authenticated/cms'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/demo-requests'
    | '/_authenticated/enterprise-requirements'
    | '/_authenticated/instructor-applications'
    | '/_authenticated/leads'
    | '/_authenticated/newsletter'
    | '/_authenticated/products'
    | '/_authenticated/profile'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/system-health'
    | '/_authenticated/users'
    | '/_site/about'
    | '/_site/contact'
    | '/_site/'
    | '/_site/blog/$slug'
    | '/_site/products/$slug'
    | '/_site/services/$slug'
    | '/_site/training/$slug'
    | '/_site/blog/'
    | '/_site/products/'
    | '/_site/services/'
    | '/_site/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/blogs': {
      id: '/_authenticated/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof AuthenticatedBlogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/book-calls': {
      id: '/_authenticated/book-calls'
      path: '/book-calls'
      fullPath: '/book-calls'
      preLoaderRoute: typeof AuthenticatedBookCallsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cms': {
      id: '/_authenticated/cms'
      path: '/cms'
      fullPath: '/cms'
      preLoaderRoute: typeof AuthenticatedCmsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo-requests': {
      id: '/_authenticated/demo-requests'
      path: '/demo-requests'
      fullPath: '/demo-requests'
      preLoaderRoute: typeof AuthenticatedDemoRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enterprise-requirements': {
      id: '/_authenticated/enterprise-requirements'
      path: '/enterprise-requirements'
      fullPath: '/enterprise-requirements'
      preLoaderRoute: typeof AuthenticatedEnterpriseRequirementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/instructor-applications': {
      id: '/_authenticated/instructor-applications'
      path: '/instructor-applications'
      fullPath: '/instructor-applications'
      preLoaderRoute: typeof AuthenticatedInstructorApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/newsletter': {
      id: '/_authenticated/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof AuthenticatedNewsletterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/system-health': {
      id: '/_authenticated/system-health'
      path: '/system-health'
      fullPath: '/system-health'
      preLoaderRoute: typeof AuthenticatedSystemHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/': {
      id: '/_site/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof SiteProductsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/products/$slug': {
      id: '/_site/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof SiteProductsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/': {
      id: '/_site/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof SiteServicesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/$slug': {
      id: '/_site/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof SiteServicesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/training/': {
      id: '/_site/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof SiteTrainingIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/training/$slug': {
      id: '/_site/training/$slug'
      path: '/training/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof SiteTrainingSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedBlogsRoute: typeof AuthenticatedBlogsRoute
  AuthenticatedBookCallsRoute: typeof AuthenticatedBookCallsRoute
  AuthenticatedCmsRoute: typeof AuthenticatedCmsRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemoRequestsRoute: typeof AuthenticatedDemoRequestsRoute
  AuthenticatedEnterpriseRequirementsRoute: typeof AuthenticatedEnterpriseRequirementsRoute
  AuthenticatedInstructorApplicationsRoute: typeof AuthenticatedInstructorApplicationsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNewsletterRoute: typeof AuthenticatedNewsletterRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSystemHealthRoute: typeof AuthenticatedSystemHealthRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedBlogsRoute: AuthenticatedBlogsRoute,
  AuthenticatedBookCallsRoute: AuthenticatedBookCallsRoute,
  AuthenticatedCmsRoute: AuthenticatedCmsRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemoRequestsRoute: AuthenticatedDemoRequestsRoute,
  AuthenticatedEnterpriseRequirementsRoute:
    AuthenticatedEnterpriseRequirementsRoute,
  AuthenticatedInstructorApplicationsRoute:
    AuthenticatedInstructorApplicationsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNewsletterRoute: AuthenticatedNewsletterRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSystemHealthRoute: AuthenticatedSystemHealthRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteProductsSlugRoute: typeof SiteProductsSlugRoute
  SiteServicesSlugRoute: typeof SiteServicesSlugRoute
  SiteTrainingSlugRoute: typeof SiteTrainingSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteProductsIndexRoute: typeof SiteProductsIndexRoute
  SiteServicesIndexRoute: typeof SiteServicesIndexRoute
  SiteTrainingIndexRoute: typeof SiteTrainingIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteProductsSlugRoute: SiteProductsSlugRoute,
  SiteServicesSlugRoute: SiteServicesSlugRoute,
  SiteTrainingSlugRoute: SiteTrainingSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteProductsIndexRoute: SiteProductsIndexRoute,
  SiteServicesIndexRoute: SiteServicesIndexRoute,
  SiteTrainingIndexRoute: SiteTrainingIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
