/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteBlogPostsRouteImport } from './routes/_site/blog-posts'
import { Route as SiteCareerRouteImport } from './routes/_site/career'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as SiteFaqRouteImport } from './routes/_site/faq'
import { Route as SiteOurClientsRouteImport } from './routes/_site/our-clients'
import { Route as SiteSoftwareSupportRouteImport } from './routes/_site/software-support'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActivityRouteImport } from './routes/admin/activity'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminBookCallsRouteImport } from './routes/admin/book-calls'
import { Route as AdminCareersRouteImport } from './routes/admin/careers'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as AdminConsultantsRouteImport } from './routes/admin/consultants'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminDemoRequestsRouteImport } from './routes/admin/demo-requests'
import { Route as AdminDigitalContentRouteImport } from './routes/admin/digital-content'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminIndustriesRouteImport } from './routes/admin/industries'
import { Route as AdminInstructorApplicationsRouteImport } from './routes/admin/instructor-applications'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminServicesRouteImport } from './routes/admin/services'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSystemHealthRouteImport } from './routes/admin/system-health'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as SiteBlogPostsSlugRouteImport } from './routes/_site/blog-posts.$slug'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog.index'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'
import { Route as SiteIndustriesSlugRouteImport } from './routes/_site/industries.$slug'
import { Route as SiteServicesIndexRouteImport } from './routes/_site/services.index'
import { Route as SiteServicesSlugRouteImport } from './routes/_site/services.$slug'
import { Route as SiteTrainingIndexRouteImport } from './routes/_site/training.index'
import { Route as SiteTrainingSlugRouteImport } from './routes/_site/training.$slug'
import { Route as AdminClientsIndexRouteImport } from './routes/admin/clients/index'
import { Route as AdminClientsIndustryNameRouteImport } from './routes/admin/clients.$industryName'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogPostsRoute = SiteBlogPostsRouteImport.update({
  id: '/blog-posts',
  path: '/blog-posts',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCareerRoute = SiteCareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOurClientsRoute = SiteOurClientsRouteImport.update({
  id: '/our-clients',
  path: '/our-clients',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSoftwareSupportRoute = SiteSoftwareSupportRouteImport.update({
  id: '/software-support',
  path: '/software-support',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookCallsRoute = AdminBookCallsRouteImport.update({
  id: '/book-calls',
  path: '/book-calls',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareersRoute = AdminCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsultantsRoute = AdminConsultantsRouteImport.update({
  id: '/consultants',
  path: '/consultants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDemoRequestsRoute = AdminDemoRequestsRouteImport.update({
  id: '/demo-requests',
  path: '/demo-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDigitalContentRoute = AdminDigitalContentRouteImport.update({
  id: '/digital-content',
  path: '/digital-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndustriesRoute = AdminIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstructorApplicationsRoute =
  AdminInstructorApplicationsRouteImport.update({
    id: '/instructor-applications',
    path: '/instructor-applications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const SiteBlogPostsSlugRoute = SiteBlogPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SiteBlogPostsRoute,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteIndustriesSlugRoute = SiteIndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesIndexRoute = SiteServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesSlugRoute = SiteServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrainingIndexRoute = SiteTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrainingSlugRoute = SiteTrainingSlugRouteImport.update({
  id: '/training/$slug',
  path: '/training/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminClientsIndexRoute = AdminClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsIndustryNameRoute =
  AdminClientsIndustryNameRouteImport.update({
    id: '/clients/$industryName',
    path: '/clients/$industryName',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/about': typeof SiteAboutRoute
  '/blog-posts': typeof SiteBlogPostsRouteWithChildren
  '/career': typeof SiteCareerRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/our-clients': typeof SiteOurClientsRoute
  '/software-support': typeof SiteSoftwareSupportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/book-calls': typeof AdminBookCallsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/digital-content': typeof AdminDigitalContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/instructor-applications': typeof AdminInstructorApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/blog-posts/$slug': typeof SiteBlogPostsSlugRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/industries/$slug': typeof SiteIndustriesSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/training/$slug': typeof SiteTrainingSlugRoute
  '/admin/clients/$industryName': typeof AdminClientsIndustryNameRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/services/': typeof SiteServicesIndexRoute
  '/training/': typeof SiteTrainingIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof SiteAboutRoute
  '/blog-posts': typeof SiteBlogPostsRouteWithChildren
  '/career': typeof SiteCareerRoute
  '/contact': typeof SiteContactRoute
  '/faq': typeof SiteFaqRoute
  '/our-clients': typeof SiteOurClientsRoute
  '/software-support': typeof SiteSoftwareSupportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/book-calls': typeof AdminBookCallsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/digital-content': typeof AdminDigitalContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/instructor-applications': typeof AdminInstructorApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog-posts/$slug': typeof SiteBlogPostsSlugRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/industries/$slug': typeof SiteIndustriesSlugRoute
  '/services/$slug': typeof SiteServicesSlugRoute
  '/training/$slug': typeof SiteTrainingSlugRoute
  '/admin/clients/$industryName': typeof AdminClientsIndustryNameRoute
  '/blog': typeof SiteBlogIndexRoute
  '/services': typeof SiteServicesIndexRoute
  '/training': typeof SiteTrainingIndexRoute
  '/admin/clients': typeof AdminClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog-posts': typeof SiteBlogPostsRouteWithChildren
  '/_site/career': typeof SiteCareerRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/our-clients': typeof SiteOurClientsRoute
  '/_site/software-support': typeof SiteSoftwareSupportRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/book-calls': typeof AdminBookCallsRoute
  '/admin/careers': typeof AdminCareersRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/consultants': typeof AdminConsultantsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/demo-requests': typeof AdminDemoRequestsRoute
  '/admin/digital-content': typeof AdminDigitalContentRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/instructor-applications': typeof AdminInstructorApplicationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/blog-posts/$slug': typeof SiteBlogPostsSlugRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/industries/$slug': typeof SiteIndustriesSlugRoute
  '/_site/services/$slug': typeof SiteServicesSlugRoute
  '/_site/training/$slug': typeof SiteTrainingSlugRoute
  '/admin/clients/$industryName': typeof AdminClientsIndustryNameRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/_site/services/': typeof SiteServicesIndexRoute
  '/_site/training/': typeof SiteTrainingIndexRoute
  '/admin/clients/': typeof AdminClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/about'
    | '/blog-posts'
    | '/career'
    | '/contact'
    | '/faq'
    | '/our-clients'
    | '/software-support'
    | '/admin/activity'
    | '/admin/blogs'
    | '/admin/book-calls'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/consultants'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/digital-content'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/instructor-applications'
    | '/admin/leads'
    | '/admin/newsletter'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/admin/'
    | '/blog-posts/$slug'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/training/$slug'
    | '/admin/clients/$industryName'
    | '/blog/'
    | '/services/'
    | '/training/'
    | '/admin/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/blog-posts'
    | '/career'
    | '/contact'
    | '/faq'
    | '/our-clients'
    | '/software-support'
    | '/admin/activity'
    | '/admin/blogs'
    | '/admin/book-calls'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/consultants'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/digital-content'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/instructor-applications'
    | '/admin/leads'
    | '/admin/newsletter'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/blog-posts/$slug'
    | '/blog/$slug'
    | '/industries/$slug'
    | '/services/$slug'
    | '/training/$slug'
    | '/admin/clients/$industryName'
    | '/blog'
    | '/services'
    | '/training'
    | '/admin/clients'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/login'
    | '/_site/about'
    | '/_site/blog-posts'
    | '/_site/career'
    | '/_site/contact'
    | '/_site/faq'
    | '/_site/our-clients'
    | '/_site/software-support'
    | '/admin/activity'
    | '/admin/blogs'
    | '/admin/book-calls'
    | '/admin/careers'
    | '/admin/cms'
    | '/admin/consultants'
    | '/admin/courses'
    | '/admin/demo-requests'
    | '/admin/digital-content'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/instructor-applications'
    | '/admin/leads'
    | '/admin/newsletter'
    | '/admin/profile'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/system-health'
    | '/admin/users'
    | '/_site/'
    | '/admin/'
    | '/_site/blog-posts/$slug'
    | '/_site/blog/$slug'
    | '/_site/industries/$slug'
    | '/_site/services/$slug'
    | '/_site/training/$slug'
    | '/admin/clients/$industryName'
    | '/_site/blog/'
    | '/_site/services/'
    | '/_site/training/'
    | '/admin/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog-posts': {
      id: '/_site/blog-posts'
      path: '/blog-posts'
      fullPath: '/blog-posts'
      preLoaderRoute: typeof SiteBlogPostsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/career': {
      id: '/_site/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof SiteCareerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/our-clients': {
      id: '/_site/our-clients'
      path: '/our-clients'
      fullPath: '/our-clients'
      preLoaderRoute: typeof SiteOurClientsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/software-support': {
      id: '/_site/software-support'
      path: '/software-support'
      fullPath: '/software-support'
      preLoaderRoute: typeof SiteSoftwareSupportRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/book-calls': {
      id: '/admin/book-calls'
      path: '/book-calls'
      fullPath: '/admin/book-calls'
      preLoaderRoute: typeof AdminBookCallsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/careers': {
      id: '/admin/careers'
      path: '/careers'
      fullPath: '/admin/careers'
      preLoaderRoute: typeof AdminCareersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consultants': {
      id: '/admin/consultants'
      path: '/consultants'
      fullPath: '/admin/consultants'
      preLoaderRoute: typeof AdminConsultantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/demo-requests': {
      id: '/admin/demo-requests'
      path: '/demo-requests'
      fullPath: '/admin/demo-requests'
      preLoaderRoute: typeof AdminDemoRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/digital-content': {
      id: '/admin/digital-content'
      path: '/digital-content'
      fullPath: '/admin/digital-content'
      preLoaderRoute: typeof AdminDigitalContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industries': {
      id: '/admin/industries'
      path: '/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AdminIndustriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instructor-applications': {
      id: '/admin/instructor-applications'
      path: '/instructor-applications'
      fullPath: '/admin/instructor-applications'
      preLoaderRoute: typeof AdminInstructorApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/blog-posts/$slug': {
      id: '/_site/blog-posts/$slug'
      path: '/$slug'
      fullPath: '/blog-posts/$slug'
      preLoaderRoute: typeof SiteBlogPostsSlugRouteImport
      parentRoute: typeof SiteBlogPostsRoute
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/industries/$slug': {
      id: '/_site/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof SiteIndustriesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/': {
      id: '/_site/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof SiteServicesIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services/$slug': {
      id: '/_site/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof SiteServicesSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/training/': {
      id: '/_site/training/'
      path: '/training'
      fullPath: '/training/'
      preLoaderRoute: typeof SiteTrainingIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/training/$slug': {
      id: '/_site/training/$slug'
      path: '/training/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof SiteTrainingSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/clients/': {
      id: '/admin/clients/'
      path: '/clients'
      fullPath: '/admin/clients/'
      preLoaderRoute: typeof AdminClientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients/$industryName': {
      id: '/admin/clients/$industryName'
      path: '/clients/$industryName'
      fullPath: '/admin/clients/$industryName'
      preLoaderRoute: typeof AdminClientsIndustryNameRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface SiteBlogPostsRouteChildren {
  SiteBlogPostsSlugRoute: typeof SiteBlogPostsSlugRoute
}

const SiteBlogPostsRouteChildren: SiteBlogPostsRouteChildren = {
  SiteBlogPostsSlugRoute: SiteBlogPostsSlugRoute,
}

const SiteBlogPostsRouteWithChildren = SiteBlogPostsRoute._addFileChildren(
  SiteBlogPostsRouteChildren,
)

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogPostsRoute: typeof SiteBlogPostsRouteWithChildren
  SiteCareerRoute: typeof SiteCareerRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteOurClientsRoute: typeof SiteOurClientsRoute
  SiteSoftwareSupportRoute: typeof SiteSoftwareSupportRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteIndustriesSlugRoute: typeof SiteIndustriesSlugRoute
  SiteServicesSlugRoute: typeof SiteServicesSlugRoute
  SiteTrainingSlugRoute: typeof SiteTrainingSlugRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
  SiteServicesIndexRoute: typeof SiteServicesIndexRoute
  SiteTrainingIndexRoute: typeof SiteTrainingIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogPostsRoute: SiteBlogPostsRouteWithChildren,
  SiteCareerRoute: SiteCareerRoute,
  SiteContactRoute: SiteContactRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteOurClientsRoute: SiteOurClientsRoute,
  SiteSoftwareSupportRoute: SiteSoftwareSupportRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteIndustriesSlugRoute: SiteIndustriesSlugRoute,
  SiteServicesSlugRoute: SiteServicesSlugRoute,
  SiteTrainingSlugRoute: SiteTrainingSlugRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
  SiteServicesIndexRoute: SiteServicesIndexRoute,
  SiteTrainingIndexRoute: SiteTrainingIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminBookCallsRoute: typeof AdminBookCallsRoute
  AdminCareersRoute: typeof AdminCareersRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminConsultantsRoute: typeof AdminConsultantsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDemoRequestsRoute: typeof AdminDemoRequestsRoute
  AdminDigitalContentRoute: typeof AdminDigitalContentRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminIndustriesRoute: typeof AdminIndustriesRoute
  AdminInstructorApplicationsRoute: typeof AdminInstructorApplicationsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsIndustryNameRoute: typeof AdminClientsIndustryNameRoute
  AdminClientsIndexRoute: typeof AdminClientsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminBookCallsRoute: AdminBookCallsRoute,
  AdminCareersRoute: AdminCareersRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminConsultantsRoute: AdminConsultantsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDemoRequestsRoute: AdminDemoRequestsRoute,
  AdminDigitalContentRoute: AdminDigitalContentRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminIndustriesRoute: AdminIndustriesRoute,
  AdminInstructorApplicationsRoute: AdminInstructorApplicationsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsIndustryNameRoute: AdminClientsIndustryNameRoute,
  AdminClientsIndexRoute: AdminClientsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
